FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "consumer.main:app", "--host", "0.0.0.0", "--port", "8080"]
CMD ["python", "consumer/consume.py"]